- hosts: localhost
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name:
          - docker.io
          - python3-docker
          - docker-compose
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Prometheus config directory
      file:
        path: /etc/prometheus
        state: directory
        mode: "0755"

    - name: Copy Prometheus configuration
      copy:
        src: files/prometheus.yml
        dest: /etc/prometheus/prometheus.yml

    - name: Create Grafana data directory
      file:
        path: /var/lib/grafana
        state: directory
        mode: "0755"

    - name: Copy Docker Compose file
      copy:
        src: "{{ playbook_dir }}/../docker/management/monitoring/docker-compose.yml"
        dest: /opt/monitoring/docker-compose.yml

    - name: Deploy monitoring stack with Docker Compose
      command: docker-compose -f /opt/monitoring/docker-compose.yml up -d
      args:
        chdir: /opt/monitoring
