name: Deploy Homelab Infrastructure
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    env:
      TF_VAR_proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}
      TF_VAR_unifi_username: ${{ secrets.UNIFI_USERNAME }}
      TF_VAR_unifi_password: ${{ secrets.UNIFI_PASSWORD }}
      TF_VAR_udm_ip: ${{ secrets.UDM_IP }}
      TF_VAR_truenas_api_key: ${{ secrets.TRUENAS_API_KEY }}
      TF_VAR_truenas_nfs_ip: ${{ secrets.TRUENAS_NFS_IP }}
      TF_VAR_proxmox_ip: ${{ secrets.PROXMOX_IP }}
      TF_VAR_proxmox_api_token_id: ${{ secrets.PROXMOX_API_TOKEN_ID }}
      TF_VAR_proxmox_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
      TF_VAR_personal_devices_passphrase: ${{ secrets.PERSONAL_DEVICES_PASSPHRASE }}
      TF_VAR_iot_passphrase: ${{ secrets.IOT_PASSPHRASE }}
      TF_VAR_guest_passphrase: ${{ secrets.GUEST_PASSPHRASE }}
      TF_VAR_lxc_password: ${{ secrets.LXC_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run terraform init
        run: /usr/bin/terraform init
        working-directory: terraform
      - name: Run terraform apply
        run: /usr/bin/terraform apply -auto-approve
        working-directory: terraform
      - name: Generate Ansible inventory
        run: |
          jq -r '.lxc_inventory.value' terraform.tfstate | tee inventory.json
          echo "[management]" > inventory.ini
          jq -r '.management.services[].ip' inventory.json >> inventory.ini
          echo "[lovvorn]" >> inventory.ini
          echo "[lovvorn_nextcloud]" >> inventory.ini
          jq -r '.lovvorn.services.nextcloud.ip' inventory.json >> inventory.ini
          echo "[shepherdscall]" >> inventory.ini
          echo "[shepherdscall_nextcloud]" >> inventory.ini
          jq -r '.shepherdscall.services.nextcloud.ip' inventory.json >> inventory.ini
          jq -r '.nfs_paths.value' terraform.tfstate | tee nfs_paths.json
        working-directory: terraform
      - name: Run Ansible playbook
        run: ansible-playbook -i inventory.ini --extra-vars "@vars.yml" playbook.yml
        working-directory: terraform/ansible
